# border_size adjusts the thickness of the borders in pixels
border_size: 2
# border_offset adjusts how much to shrink or expand the border by in pixels to better fit the size of the window
border_offset: -1
# border_radius lets you set your own custom radius for the border in pixels. Leave it at -1 to let the program handle the radius, or set it to anything other than -1 to use as the radius.
border_radius: -1 

window_rules:
  - match: "Global"
    active_color: "gradient(#89b4fa, #CBA6F7, 0%, 0%, 100%, 0%)"
    inactive_color: "#1E1E2E"
  - match: "Class"
    contains: "Windows.UI.Core.CoreWindow"
    enabled: false
  - match: "Title"
    contains: "Flow.Launcher"
    enabled: false
  - match: "Title"
    contains: "Zebar"
    enabled: false