# yaml-language-server: $schema=https://raw.githubusercontent.com/GlazeBar/tacky-borders/refs/heads/main/schema.json
# border_size: Defines the thickness of the borders in pixels around each window.
# Example: 2 indicates a 2-pixel-thick border.
border_size: 2

# border_offset: Adjusts the border position by shrinking or expanding it relative to the window.
#   - Negative values shrink the border inward, effectively reducing the visible border size.
#   - Positive values expand the border outward.
# Example: -1 slightly reduces the border’s coverage.
border_offset: -1

# border_radius: Sets a custom radius for the window border’s rounded corners.
#   - Use -1 to let the application automatically handle the radius.
#   - Any positive value will apply a fixed radius in pixels to the window corners.
# Example: 5 would apply a 5-pixel corner radius.
border_radius: -1

# window_rules
# Defines how the borders behave based on specific properties of the windows.
# match:
# - Global: Applies globally unless overridden by more specific rules.
# - Class: Applies based on the window's class name.
# - Title: Applies based on the window title.

# match_strategies (default: Equals):
# - "Equals": The match value must be exactly equal to the specified value.
# - "Regex": The match value must match the specified regular expression.
# - "Contains": The match value must be a substring of the specified string.

# match_value:
# - Specifies the value against which the window's properties are matched.
# - Can be a string that must either match exactly, be a substring, or conform to a regex pattern
#   depending on the specified match strategy.

# border_enabled (default: true):
# - A boolean value indicating whether the border is enabled for this particular rule.
# - If true, the defined border properties (such as color and thickness) will apply to matching windows.
# - If false, no border will be applied, effectively disabling it for that rule.

# Color Definitions:
# - active_color: The color used for the active window border.
#   - Can be specified as a string or a map format.
#   - If using a map, provide colors in various formats: #RRGGBB, #RRGGBBAA, rgb(...), or rgba(...).
#     - colors: A list of color values to define the active border colors.
#     - direction: Specifies the start and end points of a linear gradient for the border.
#       - direction:
#         - 0.0 # Starting point of the gradient x-axis.
#         - 0.0 # Starting point of the gradient y-axis.
#         - 1.0 # Endpoint of the gradient x-axis.
#         - 1.0 # Endpoint of the gradient y-axis.
#     - animation: Boolean value indicating whether to animate the color transition.
# - inactive_color: The color used for inactive window borders.
#   - Can also be specified as a string or a map format with similar color options.
window_rules:
  - match: "Global"
    active_color:
      colors:
        - "#000000"
        - "#FFFFFF"
      direction:
        - 0.0
        - 0.0
        - 1.0
        - 1.0
    inactive_color: "accent"
  
  - match: "Class"
    match_value: "Windows.UI.Core.CoreWindow"
    match_strategy: "Contains"
    border_enabled: false

  - match: "Title"
    match_value: "(?i)^Flow.*"
    match_strategy: "Regex" 
    border_enabled: false

  - match: "Title"
    match_value: "Zebar"
    match_strategy: "Equals"
    border_enabled: false
