# Border configuration settings

# Valid colors:
# - hex (e.g., #ffffff for white)
# - hexa (e.g., #ffffff80 for semi transparent white)
# - rgb (e.g., rgb(0, 0, 0) for black)
# - rgba (e.g., rgba(255, 0, 0, 0.5) for semi transparent red)

border_size: 2

# border_offset: Adjusts border size in pixels (default: -1).
# Example: -2 reduces size by 2 pixels; 1 increases by 1 pixel.
border_offset: -1

# border_radius: Custom radius for borders in pixels; -1 for auto (default: -1).
# Example: Setting to 10 creates rounded corners.
border_radius: -1 

# window_rules: Conditions for applying border settings to specific windows.
window_rules:
  - match: "Global"  # Applies to all windows
    active_color: "gradient(#89b4fa, #CBA6F7, 0%, 0%, 100%, 0%)"  # Active border gradient
    inactive_color: "#1E1E2E"  # Inactive border color
  
  - match: "Class"  # Specific class targeting
    contains: "Windows.UI.Core.CoreWindow"  # Matches class name
    enabled: false  # Rule is disabled

  - match: "Title"  # Specific title targeting
    contains: "Flow.Launcher"  # Matches window title
    enabled: false  # Rule is disabled

  - match: "Title"  # Another title targeting
    contains: "Zebar"  # Matches window title
    enabled: false  # Rule is disabled